global:
  resolve_timeout: 5m
receivers:
- name: prometheus-msteams
  webhook_configs:
  - url: "https://webhook-microsoft-teams"
    send_resolved: true
route:
  group_by:
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: prometheus-msteams
  repeat_interval: 1h
  routes:
  - match:
      alertname: Monitoring and Servers
    receiver: prometheus-msteams
