version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

services:

  grafana:
    image: grafana/grafana:8.5.10-ubuntu
    user: root
    volumes:
      - ${STACK_VOLUME}/grafana/data:/var/lib/grafana
      - ${STACK_VOLUME}/grafana/imagens:/usr/share/grafana/public/imagens
    environment:
      - TZ=America/Sao_Paulo
      - GF_INSTALL_PLUGINS=${INSTALL_PLUGINS}
      - GF_SERVER_ROOT_URL=${URL_GRAFANA}
     #- GF_INSTALL_IMAGE_RENDERER_PLUGIN=true
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${SMTP_HOST}
      - GF_SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - GF_SMTP_EHLO_IDENTITY=${SMTP_EHLO}
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=${ALLOW_LOADING_UNSIGNED_PLUGINS}
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 2048M
        reservations:
          memory: 1024M
          cpus: "0.5"
    ports:
      - 49200:3000
    networks:
      - net
      
  prometheus:
    image: prom/prometheus:v2.40.7
    environment:
      - TZ=America/Sao_Paulo
    user: root
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=${PROMETHEUS_RETENTION}'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

    volumes:
      - ${STACK_VOLUME}/prometheus/data/:/prometheus/:rw
      - ${STACK_VOLUME}/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:rw
      - ${STACK_VOLUME}/prometheus/config/alert.rules:/etc/prometheus/alert.rules:rw
    deploy:

      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 256M
        reservations:
          memory: 256M
          cpus: "0.5"
    ports:
      - 49300:9090
    networks:
      - net
    
  alertmanager:
    image: prom/alertmanager:v0.23.0
    environment:
      - TZ=America/Sao_Paulo
    user: root
    volumes:
      - ${STACK_VOLUME}/alertmanager/data/:/alertmanager/:rw
      - ${STACK_VOLUME}/alertmanager/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml:rw
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.25"
          memory: 96M
        reservations:
          memory: 50M
          cpus: "0.1"
    ports:
      - 49400:9093
    networks:
      - net

  prometheus-msteams:
    image: idealista/prom2teams:2.7.0
    environment:
      - PROM2TEAMS_CONNECTOR=${TEAMS_WEBHOOK}
      - TEAMS_REQUEST_URI=alertmanager
      - TZ=America/Sao_Paulo
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 96M
        reservations:
          memory: 64M
          cpus: "0.25"
    ports:
      - 49500:8089
    networks:
      - net
